# Generated by Django 2.2.11 on 2020-07-06 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='height',
        ),
    ]
