# Generated by Django 2.2.11 on 2020-07-06 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_articlecomment_height'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='height',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleComment'),
        ),
    ]
