# Generated by Django 2.2.11 on 2020-04-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thubm',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
