# Generated by Django 2.2.11 on 2020-04-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_thubm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thubm',
            new_name='thumb',
        ),
    ]
