# Generated by Django 2.2.11 on 2020-07-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlecomment_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='height',
            field=models.IntegerField(default=10),
        ),
    ]
