# Generated by Django 2.2.11 on 2020-07-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200707_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='_articlecomment_child_+', to='articles.ArticleComment'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
