# Generated by Django 2.2.11 on 2020-06-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200618_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='accounts/images/default.png', upload_to='accounts/images'),
        ),
    ]
