# Generated by Django 2.2.11 on 2022-10-19 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='meet_id',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='meet_time',
        ),
    ]
