# Generated by Django 2.2.11 on 2022-10-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20221019_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
