# Generated by Django 2.2.11 on 2022-10-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meet_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='additon_time',
            new_name='addition_time',
        ),
    ]
