# Generated by Django 2.2.11 on 2022-10-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20221019_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='linkdein_profile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meet',
            name='resume_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
