# Generated by Django 3.2.11 on 2022-11-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20221020_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='type_of_meet',
            field=models.CharField(choices=[('do', 'DSA AND OPERATING SYSTEM'), ('dd', 'DSA AND DATABASE'), ('dn', 'DSA AND NETWORKING'), ('od', 'OPERATING SYSTEM AND DATABASE')], max_length=10),
        ),
    ]
